# Generated by Django 5.1.1 on 2024-11-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('tipo', models.TextField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('cantidad_intentos', models.IntegerField(default=0)),
            ],
        ),
    ]
