# Generated by Django 5.1.1 on 2024-11-26 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('cantidad_alumnos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.TextField(max_length=13)),
                ('nombres', models.TextField(max_length=100)),
                ('paterno', models.TextField(max_length=50)),
                ('materno', models.TextField(max_length=50)),
                ('correo', models.TextField(max_length=50)),
                ('cargo', models.TextField(max_length=50)),
                ('asignatura', models.TextField(max_length=100, null=True)),
                ('jefatura', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('cantidad_intentos', models.IntegerField(default=0)),
                ('password', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.TextField(max_length=13)),
                ('nombres', models.TextField(max_length=100)),
                ('paterno', models.TextField(max_length=50)),
                ('materno', models.TextField(max_length=50)),
                ('edad', models.IntegerField()),
                ('promedio_anterior', models.IntegerField()),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matriculas.curso')),
                ('nacionalidades', models.ManyToManyField(to='matriculas.nacionalidad')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor_jefe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesor_jege', to='matriculas.funcionario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesores',
            field=models.ManyToManyField(related_name='profesores', to='matriculas.funcionario'),
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.TextField(max_length=13)),
                ('nombres', models.TextField(max_length=100)),
                ('paterno', models.TextField(max_length=50)),
                ('materno', models.TextField(max_length=50)),
                ('edad', models.IntegerField()),
                ('parentesco', models.TextField(max_length=50)),
                ('nacionalidades', models.ManyToManyField(to='matriculas.nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matriculas.alumno')),
                ('apoderado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matriculas.apoderado')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matriculas.curso')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matriculas.funcionario')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='sala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matriculas.sala'),
        ),
    ]
