# Generated by Django 5.1.1 on 2024-11-27 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='profesor_jefe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matriculas.funcionario'),
        ),
    ]
