# Generated by Django 5.1.1 on 2024-11-27 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_alter_curso_profesor_jefe'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matriculas.periodo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesores',
            field=models.ManyToManyField(related_name='cursos', to='matriculas.funcionario'),
        ),
    ]
